### PR TITLE
feat($search): include Search on Category and Tag Layout´s

### PR DESCRIPTION
**Pull request by tgmti**
Hello, 

In my project i will use the specific category pages for post types separation.
So, my menu contains routes to /posts/categories/{category} (i.e. /blog, /example, /functions).

then, i included search on this layouts.

You think it´s a valid feature to master?

if not, just ignore me. no problems.

### CODE REVIEW

**Comment by meteorlxy** [comment]
That's reasonable, but we should make some refactor.

Copy and paste the related codes from `Post` to `Category` and `Tag` is not a good idea.

**Comment by tgmti** [comment]
Demo:

SearchCatTag

**Comment by tgmti** [comment]
sure,

i was think this. 
it was  just concept prove.
in fact the intention was create a draft PR, but incorrect i clicked.

**Comment by meteorlxy** [comment]
We can have further discussion on the feature/refactor after you finish 😄 

---

BTW, the links to `/posts/categories/` and `/posts/tags/` is not so obvious in our theme now.

I'm not sure if those pages are so useful, so I didn't pay much attention on them (just made them work).

If they are useful for many users, maybe we could try to make them better, or find a better way to display the links to them.

**Comment by tgmti** [comment]
in moment, i think we can implements the search in PostsList component. 
working on this to demonstrate

**Comment by tgmti** [comment]
now looks´t better, but css it´s my sadness.

have you a hint to improve this? 😞 

SearchPostList

**Comment by tgmti** [comment]
I changed.

Search in all pages with posts

- implements PostsMain (todo: change this name), as a component.
- the PostsMain has categories, tags and search, surrounded with props
- component used in Home, Posts, Category and Tag layouts

what you say?

SearchInPostsMainComponent

**Comment by meteorlxy** [comment]
I just made some refactor:

- Put the `no-related-posts` into `<PostsList>`
- Extract a `<PostFilter>` component to decouple the list and the filter

Your solution is an alternative way, too. I'm not sure if my refactor is better.

**Comment by meteorlxy** [comment]
Thanks @tgmti 

I just merged it. Feel free to open issues/PRs if you have any ideas. 😄

**Comment by tgmti** [comment]
ok,

i´m looking way to include it in 'Home' layout to, but using 'themeConfig' to supress, for use without default layout break.

btw, I send in a new PR when get success.

tnk´s man. :relaxed: 👍

**Pull request merged**
