### PR TITLE
fix(postslistitem.vue): color of category and tags not change by hover

### PR DESCRIPTION
**Pull request by caohenghu**

### CODE REVIEW

**Comment by meteorlxy** [comment]
Sorry for delay.

It looks a little strange for the different behaviors of category and tags:

image

image

**Comment by caohenghu** [comment]
QQ20200327-132855
here

**Comment by meteorlxy** [comment]
Yes, that's the initial reason why I didn't change the hovered color 😅

**Comment by caohenghu** [comment]
没明白，明明可以点击，hover时颜色却不变，这样有什么好呢？

**Pull request closed without merging**
