### PR TITLE
feat($search): Filter on Home with themeConfig

### PR DESCRIPTION
**Pull request by tgmti**
- Filter component Support on Home Layout;
- Allow enable this feature on themeConfig.homeFilters;
- Allow configure Categories, Tags and Search separated;
- Default state of this Filters it´s disabled.

SearchInHomeConfigurable

### CODE REVIEW

**Comment by meteorlxy** [comment]
I wonder if we should make it as a theme level config.

In fact, we can create a `src/index.md` to have similar feature like this PR:

```yaml
# src/index.md
---
layout: Posts
---
```

---

I was thinking about how to make the `<Home>` layout better. For now, `<Home>` looks like a simplified version of `<Posts>`.

Even we add this feature, `<Home>` still looks like another `<Posts>`, too.

**Comment by meteorlxy** [comment]
I've added docs about custom layout [here](https://github.com/meteorlxy/vuepress-theme-meteorlxy/commit/350945bebe22fe81428a1573c9b3fe7e807185f9)

**Comment by tgmti** [comment]
About Home I agree, in fact in my project I disabled the posts page.

But, on second thought, this ends up behaving just like a blog, and I do not seem to be the purpose of this theme.

It seems to me that it is important to search the entire site.
But, I will rethink my Home, or use CustomLayout for that..

---------------

Anyway, I've learned a lot by working on it.
And thank you very much for that.

In the next changes, I'll open a issue before a PR.

**Comment by meteorlxy** [comment]
Some features need some discussion before implementation. Issue first would avoid wasting your time.

Anyway, you can customize this theme in your own fork as you like 😄 .

**Comment by tgmti** [comment]
True, I using my fork as submodule on my page.
It's working fine, and easyly to customize.

Closing this PR.

**Pull request closed without merging**
